integrations:
  # Create a separate integration per combination of
  #   <team>-<source_kind>-<target-kind>

  - name: ***REMOVED***-bb1-to-gh3
    enabled: true
    sync:
      type: loop
      period_seconds: 600
    source:
      type: bitbucket
      base_url: https://***REMOVED***
      # `kind` format varies depending on type: Bitbucket or Github
      #   Bitbucket supports `project/<name>` and `user/<name>`
      #   Github supports `org/<name>` and `user/<name>`
      kind: project/***REMOVED***
      repos:
        # List of filters to be evaluated in order.
        #   Order does not matter other than includes are processed before excludes
        #   Regexes implied by leading and trailing `/`
        filters:
          include:
            - ***REMOVED***
            - /^.*-***REMOVED***$/
          exclude:
            - ***REMOVED***
            - /***REMOVED***/
    target:
      type: github-enterprise
      base_url: https://***REMOVED***
      # org/***REMOVED*** seems more coherent with the rest like project/***REMOVED***, user/***REMOVED***
      kind: org/***REMOVED***
      # teams are list of teams to add (no pattern support)
      teams:
        read_only:
          - ***REMOVED***
        read_write:
          - ***REMOVED***
      users:
        read_only:
          - user-id-1
        read_write:
          - user-id-2
      # branch_modifiers allow you to rewrite target repo names
      #   By default, empty branch_modifies sync exactly the same branch names from source to target
      branch_modifiers:
        - name: master-branch-only
          # match can accept regex implied by leading and trailing `/`
          match: master
          prefix: bb-

    # Example (no need to implement):
    # - name: all-branches-except-master
    #   match: /^(?!master).*/
    #   prefix: bb-
    # Example (no need to implement):
    # - name: all-branches
    #   match: /.*/
    #   prefix: bb-
    # Example (no need to implement):
    # - name: rename-branch
    #   match: featureX
    #   rename: featureY
  - name: personal-***REMOVED***-bb-to-gh3
    enabled: false
    sync:
      type: once
      period_seconds: 0
    source:
      type: bitbucket
      base_url: https://***REMOVED***
      kind: user/***REMOVED***
      repos:
        filters:
          include:
            - /.*/
          exclude: []
    target:
      type: github-enterprise
      base_url: https://***REMOVED***
      kind: user/***REMOVED***
      branch_modifiers: []

  - name: ***REMOVED***sso-github.com-to-gh3
    enabled: true
    sync:
      type: loop
      period_seconds: 600
    source:
      type: github-public
      base_url: https://www.github.com
      kind: org/***REMOVED***
      repos:
        filters:
          include:
            - /.*/
          exclude: []
    target:
      type: github-enterprise
      base_url: https://***REMOVED***
      kind: org/***REMOVED***
      branch_modifiers: []
